/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonSlugRouteImport } from './routes/lesson.$slug'
import { Route as learnerProgressRouteImport } from './routes/(learner)/progress'
import { Route as DashboardModeratorIndexRouteImport } from './routes/dashboard/moderator/index'
import { Route as DashboardAuthorIndexRouteImport } from './routes/dashboard/author/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminContentRouteImport } from './routes/dashboard/admin/content'
import { Route as subjectsSubjectsSlugRouteImport } from './routes/(subjects)/subjects.$slug'
import { Route as learnerSubjectsIntermediateRouteImport } from './routes/(learner)/subjects.intermediate'
import { Route as learnerSubjectsAdvancedRouteImport } from './routes/(learner)/subjects.advanced'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSlugRoute = LessonSlugRouteImport.update({
  id: '/lesson/$slug',
  path: '/lesson/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const learnerProgressRoute = learnerProgressRouteImport.update({
  id: '/(learner)/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModeratorIndexRoute = DashboardModeratorIndexRouteImport.update({
  id: '/dashboard/moderator/',
  path: '/dashboard/moderator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthorIndexRoute = DashboardAuthorIndexRouteImport.update({
  id: '/dashboard/author/',
  path: '/dashboard/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminContentRoute = DashboardAdminContentRouteImport.update({
  id: '/dashboard/admin/content',
  path: '/dashboard/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const subjectsSubjectsSlugRoute = subjectsSubjectsSlugRouteImport.update({
  id: '/(subjects)/subjects/$slug',
  path: '/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const learnerSubjectsIntermediateRoute =
  learnerSubjectsIntermediateRouteImport.update({
    id: '/(learner)/subjects/intermediate',
    path: '/subjects/intermediate',
    getParentRoute: () => rootRouteImport,
  } as any)
const learnerSubjectsAdvancedRoute = learnerSubjectsAdvancedRouteImport.update({
  id: '/(learner)/subjects/advanced',
  path: '/subjects/advanced',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subjects': typeof SubjectsRoute
  '/progress': typeof learnerProgressRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/subjects/advanced': typeof learnerSubjectsAdvancedRoute
  '/subjects/intermediate': typeof learnerSubjectsIntermediateRoute
  '/subjects/$slug': typeof subjectsSubjectsSlugRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/author/': typeof DashboardAuthorIndexRoute
  '/dashboard/moderator/': typeof DashboardModeratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subjects': typeof SubjectsRoute
  '/progress': typeof learnerProgressRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/subjects/advanced': typeof learnerSubjectsAdvancedRoute
  '/subjects/intermediate': typeof learnerSubjectsIntermediateRoute
  '/subjects/$slug': typeof subjectsSubjectsSlugRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/author': typeof DashboardAuthorIndexRoute
  '/dashboard/moderator': typeof DashboardModeratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subjects': typeof SubjectsRoute
  '/(learner)/progress': typeof learnerProgressRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/(learner)/subjects/advanced': typeof learnerSubjectsAdvancedRoute
  '/(learner)/subjects/intermediate': typeof learnerSubjectsIntermediateRoute
  '/(subjects)/subjects/$slug': typeof subjectsSubjectsSlugRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/author/': typeof DashboardAuthorIndexRoute
  '/dashboard/moderator/': typeof DashboardModeratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/subjects'
    | '/progress'
    | '/lesson/$slug'
    | '/subjects/advanced'
    | '/subjects/intermediate'
    | '/subjects/$slug'
    | '/dashboard/admin/content'
    | '/dashboard/admin/'
    | '/dashboard/author/'
    | '/dashboard/moderator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/subjects'
    | '/progress'
    | '/lesson/$slug'
    | '/subjects/advanced'
    | '/subjects/intermediate'
    | '/subjects/$slug'
    | '/dashboard/admin/content'
    | '/dashboard/admin'
    | '/dashboard/author'
    | '/dashboard/moderator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/subjects'
    | '/(learner)/progress'
    | '/lesson/$slug'
    | '/(learner)/subjects/advanced'
    | '/(learner)/subjects/intermediate'
    | '/(subjects)/subjects/$slug'
    | '/dashboard/admin/content'
    | '/dashboard/admin/'
    | '/dashboard/author/'
    | '/dashboard/moderator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubjectsRoute: typeof SubjectsRoute
  learnerProgressRoute: typeof learnerProgressRoute
  LessonSlugRoute: typeof LessonSlugRoute
  learnerSubjectsAdvancedRoute: typeof learnerSubjectsAdvancedRoute
  learnerSubjectsIntermediateRoute: typeof learnerSubjectsIntermediateRoute
  subjectsSubjectsSlugRoute: typeof subjectsSubjectsSlugRoute
  DashboardAdminContentRoute: typeof DashboardAdminContentRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAuthorIndexRoute: typeof DashboardAuthorIndexRoute
  DashboardModeratorIndexRoute: typeof DashboardModeratorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$slug': {
      id: '/lesson/$slug'
      path: '/lesson/$slug'
      fullPath: '/lesson/$slug'
      preLoaderRoute: typeof LessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learner)/progress': {
      id: '/(learner)/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof learnerProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/moderator/': {
      id: '/dashboard/moderator/'
      path: '/dashboard/moderator'
      fullPath: '/dashboard/moderator/'
      preLoaderRoute: typeof DashboardModeratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/author/': {
      id: '/dashboard/author/'
      path: '/dashboard/author'
      fullPath: '/dashboard/author/'
      preLoaderRoute: typeof DashboardAuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/content': {
      id: '/dashboard/admin/content'
      path: '/dashboard/admin/content'
      fullPath: '/dashboard/admin/content'
      preLoaderRoute: typeof DashboardAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(subjects)/subjects/$slug': {
      id: '/(subjects)/subjects/$slug'
      path: '/subjects/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof subjectsSubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learner)/subjects/intermediate': {
      id: '/(learner)/subjects/intermediate'
      path: '/subjects/intermediate'
      fullPath: '/subjects/intermediate'
      preLoaderRoute: typeof learnerSubjectsIntermediateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learner)/subjects/advanced': {
      id: '/(learner)/subjects/advanced'
      path: '/subjects/advanced'
      fullPath: '/subjects/advanced'
      preLoaderRoute: typeof learnerSubjectsAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubjectsRoute: SubjectsRoute,
  learnerProgressRoute: learnerProgressRoute,
  LessonSlugRoute: LessonSlugRoute,
  learnerSubjectsAdvancedRoute: learnerSubjectsAdvancedRoute,
  learnerSubjectsIntermediateRoute: learnerSubjectsIntermediateRoute,
  subjectsSubjectsSlugRoute: subjectsSubjectsSlugRoute,
  DashboardAdminContentRoute: DashboardAdminContentRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAuthorIndexRoute: DashboardAuthorIndexRoute,
  DashboardModeratorIndexRoute: DashboardModeratorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
